from __future__ import annotations

from pathlib import Path

import pandas as pd

from src.logging_config import configure_logging
from src.utils import infer_file_type, project_path, read_tabular_sample, sha256_file, utc_now, write_csv


LOGGER = configure_logging(__name__)


def count_tabular(path: Path) -> tuple[int | str, int | str]:
    file_type = infer_file_type(path)
    try:
        if file_type in {"csv", "tsv"}:
            sep = "\t" if file_type == "tsv" else ","
            df = read_tabular_sample(path, nrows=1000)
            row_count = sum(len(chunk) for chunk in pd.read_csv(path, sep=sep, chunksize=100000))
            return row_count, len(df.columns)
        if file_type == "parquet":
            df = pd.read_parquet(path)
            return len(df), len(df.columns)
        if file_type == "json":
            return "", ""
    except Exception as exc:
        LOGGER.warning("Could not count %s: %s", path, exc)
    return "", ""


def infer_source(path: Path) -> tuple[str, str]:
    text = str(path)
    if "/geo/" in text:
        return "NCBI GEO", "GSE2034"
    if "/cell_painting/" in text:
        return "Broad Institute Cell Painting Gallery", "cpg0000-jump-pilot/source_4/BR00116991"
    if "/openneuro/" in text:
        return "OpenNeuro", "ds004504"
    return "derived", "local"


def build_manifest() -> list[dict]:
    rows: list[dict] = []
    for stage in ["raw", "interim", "cdm", "outputs"]:
        base = project_path("data", stage)
        if not base.exists():
            continue
        for path in sorted(p for p in base.rglob("*") if p.is_file()):
            row_count, column_count = count_tabular(path)
            source_system, source_dataset = infer_source(path)
            rows.append(
                {
                    "file_path": str(path.relative_to(project_path())),
                    "source_system": source_system,
                    "source_dataset": source_dataset,
                    "file_type": infer_file_type(path),
                    "row_count": row_count,
                    "column_count": column_count,
                    "file_size_mb": round(path.stat().st_size / (1024 * 1024), 3),
                    "checksum": sha256_file(path),
                    "created_at": utc_now(),
                    "processing_stage": stage[:-1] if stage == "outputs" else stage,
                    "parent_file_path": "",
                    "processing_script": "src/build_data_manifest.py",
                    "notes": "Generated manifest entry",
                }
            )
    write_csv(rows, project_path("data", "manifests", "data_manifest.csv"))
    write_lineage_summary(rows)
    return rows


def write_lineage_summary(rows: list[dict]) -> None:
    by_stage: dict[str, int] = {}
    for row in rows:
        by_stage[row["processing_stage"]] = by_stage.get(row["processing_stage"], 0) + 1
    lines = ["# Lineage Summary", "", "This summary inventories raw, interim, CDM, and output files generated by the project.", ""]
    for stage, count in sorted(by_stage.items()):
        lines.append(f"- {stage}: {count} files")
    lines.extend(["", "Lineage columns are preserved in CDM outputs: source_system, source_dataset, source_file, source_record_id, ingestion_timestamp, and mapping_version."])
    out = project_path("data", "outputs", "lineage_summary.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    build_manifest()
